### ISSUE TITLE
add per-sample call-rate to vis

### ISSUE THREAD

**Issue by brentp** [brentp/peddy#13]
idea from @jxchong

would be nice if we had some indication of call-rate in the output. this could be indicated by the size of points in the middle plot (median depth vs proportion of HET calls).

**Comment by jxchong** [comment]
Or just add a column to the table.  No strong opinion either way.



On July 18, 2016 at 3:45:51 PM, Brent Pedersen - Bioinformatics (
notifications@github.com) wrote:

idea from @jxchong <https://github.com/jxchong>

would be nice if we had some indication of call-rate in the output. this
could be indicated by the size of points in the middle plot (median depth
vs proportion of HET calls).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brentp/peddy/issues/13>, or mute the thread
